/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--color-bg)",
        surface: "var(--color-surface)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-variant": "var(--color-surface-variant)",
        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        primary: "var(--color-primary)",
        "primary-container": "var(--color-primary-container)",
        "on-primary": "var(--color-on-primary)",
        "on-primary-container": "var(--color-on-primary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        secondary: "var(--color-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary": "var(--color-on-secondary)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        error: "var(--color-error)",
        "error-container": "var(--color-error-container)",
        "on-error": "var(--color-on-error)",
        "on-error-container": "var(--color-on-error-container)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "sidebar-width-expanded": "16rem",
        "sidebar-width-collapsed": "3.5rem",
        "layout-margin-desktop": "1.5rem",
        "layout-margin-mobile": "0.75rem",
        "layout-gutter": "1rem",
        "max-content-width": "1600px",
      },
      fontFamily: {
        display: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        body: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        code: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["1.875rem", { lineHeight: "2.25rem", fontWeight: "700" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", fontWeight: "600" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", fontWeight: "600" }],
        "headline-sm": ["1rem", { lineHeight: "1.5rem", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem" }],
        "body-md": ["0.875rem", { lineHeight: "1.375rem" }],
        "body-sm": ["0.75rem", { lineHeight: "1.125rem" }],
        "code-lg": ["1rem", { lineHeight: "1.5rem" }],
        "code-md": ["0.875rem", { lineHeight: "1.375rem" }],
        "code-sm": ["0.75rem", { lineHeight: "1.125rem" }],
        "label-caps": ["0.6875rem", { lineHeight: "1rem", letterSpacing: "0.05em" }],
      },
      boxShadow: {
        'glow-lime': '0 0 20px -3px rgba(182, 255, 46, 0.25)',
        'glow-cyan': '0 0 20px -3px rgba(123, 208, 255, 0.25)',
        'glow-red': '0 0 20px -3px rgba(255, 180, 171, 0.25)',
      }
    },
  },
  plugins: [],
}
