-- RepoLens: users table migration
-- Run this in the Supabase SQL Editor (https://supabase.com/dashboard → SQL Editor)
--
-- This table stores application-level user profiles.
-- Authentication is handled by Supabase Auth (auth.users).
-- The `id` here mirrors auth.users.id — same UUID, never duplicated.

CREATE TABLE IF NOT EXISTS public.users (
    id              UUID PRIMARY KEY,           -- mirrors auth.users.id (from verified JWT sub)
    email           TEXT UNIQUE NOT NULL,       -- from verified JWT email claim
    display_name    TEXT,
    avatar_url      TEXT,
    provider        TEXT NOT NULL DEFAULT 'email',  -- 'email' | 'github' | 'google'
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for fast email lookups (e.g. admin search)
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users (email);

-- ── Row-Level Security ────────────────────────────────────────────────────────
-- Enable RLS so that if you ever expose this table via Supabase PostgREST,
-- users can only read/update their own row.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Policy: authenticated users can only see their own row
CREATE POLICY "users: select own row"
    ON public.users
    FOR SELECT
    USING (id = auth.uid());

-- Policy: authenticated users can update their own row (not id or email)
CREATE POLICY "users: update own row"
    ON public.users
    FOR UPDATE
    USING (id = auth.uid());

-- Policy: service role (backend) can insert/upsert freely
-- The backend uses the DATABASE_URL connection (not the anon key),
-- so it bypasses RLS. This policy is for completeness if you ever
-- add a direct Supabase client call.
CREATE POLICY "users: service role insert"
    ON public.users
    FOR INSERT
    WITH CHECK (true);

-- ── Comments ──────────────────────────────────────────────────────────────────
COMMENT ON TABLE public.users IS
    'Application user profiles. id = Supabase auth.users.id. No passwords stored here.';
COMMENT ON COLUMN public.users.id IS
    'UUID from Supabase JWT sub claim — never auto-generated by this table.';
COMMENT ON COLUMN public.users.email IS
    'Verified email from Supabase JWT — populated by the backend, cannot be spoofed via API.';
COMMENT ON COLUMN public.users.provider IS
    'OAuth provider used: email | github | google';
