"""Add ingestion columns to repository

Revision ID: 5c167bc3d778
Revises: c096848e9b63
Create Date: 2026-09-06 18:48:25.268712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c167bc3d778'
down_revision: Union[str, Sequence[str], None] = 'c096848e9b63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('workspace_path', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('file_count', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('total_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'total_size_bytes')
    op.drop_column('repositories', 'file_count')
    op.drop_column('repositories', 'workspace_path')
    # ### end Alembic commands ###
