"""Add repositories table

Revision ID: c096848e9b63
Revises: 
Create Date: 2026-09-06 18:13:56.380156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c096848e9b63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('github', 'zip', name='sourcetype', create_constraint=True), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('primary_language', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('latest_commit_sha', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uix_source_type_url', 'repositories', ['source_type', 'source_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_source_type_url', table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
